id = "lume"
name = "Lume"
version = "0.0.1"
schema_version = 1
authors = ["Maciej"]
description = "Support for the Lume functional language"

languages = ["lume"]

[language_servers.lume-lsp]
name = "Lume LSP"
language = "lume"

[grammars.lume]
repository = "file:///Users/kamov/Desktop/tree-sitter-lume"
rev = "a317363f48ccf1ab35578c4a2af19ba7df43fdfa"
path = ""
