id = "lume"
name = "Lume"
version = "0.0.1"
schema_version = 1
authors = ["Maciej"]
description = "Support for the Lume functional language"

languages = ["lume"]

[language_servers.lume-lsp]
name = "Lume LSP"
language = "lume"

[grammars.lume]
repository = "https://github.com/kamoshi/tree-sitter-lume.git"
rev = "42a3592df34f36777913749419185c2beb7124c7"
