id = "lume"
name = "Lume"
version = "0.0.1"
schema_version = 1
authors = ["Maciej"]
description = "Support for the Lume functional language"

languages = ["lume"]

[language_servers.lume-lsp]
name = "Lume LSP"
language = "lume"

[grammars.lume]
repository = "file:///Users/kamov/Desktop/tree-sitter-lume"
rev = "4da4997c0a5fa909c3d6e33925b2e7ecb46aee0c"
path = ""
